# -*- coding: utf-8 -*-
"""inicial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1719grmyrAylJdmamZkQpxi8ztmBQFo_e
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Lendo o txt
df = pd.read_csv(r"/content/train.txt", sep=";")

# Renomeando colunas
df.columns = ["mensagem", "emocao"]

# Transformando em csv
df.to_csv("train.csv", index=False)

print("Arquivo convertido e salvo como csv")

df.head()